sudo: required

language: ruby

rvm:
  - 2.6.4

services:
  - postgresql

cache:
  bundler: true

addons:
  postgresql: "12.0"

before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3

before_script:
  - cp .rspec.travis .rspec
  - cp config/database.yml.travis config/database.yml
  - psql --command='CREATE DATABASE travis_ci_test;' --username=postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:create db:migrate RAILS_ENV=test
